# Generated by Django 4.1.7 on 2023-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioroom',
            name='authors',
            field=models.ManyToManyField(to='authors.authormodel'),
        ),
    ]
