# Generated by Django 4.1.7 on 2023-03-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='name',
            field=models.CharField(db_index=True, max_length=23, null=True),
        ),
    ]
