version: '3.9'
services:

  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file: .env
  #   command: python ./BookShy/manage.py runserver 0.0.0.0:8000
  #   networks:
  #     - database-network
  #   depends_on:
  #     - db
  db:
    image: kartoza/postgis:15-3.3

    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - '5432:5432'
    restart: on-failure
    networks:
      - database-network
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h db -U docker -d gis"


networks:
  database-network:
    name: database-network