# Generated by Django 4.1.7 on 2023-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='novels.novelmodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='recently_viewed_chapters',
            field=models.ManyToManyField(blank=True, null=True, related_name='recently_viewed_chapters', to='novels.chaptermodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_novels',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_novel', to='novels.novelmodel'),
        ),
    ]
