# Generated by Django 3.2 on 2021-11-14 06:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0018_auto_20211110_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=30)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NovelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('discription', models.TextField()),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.mappoint')),
            ],
        ),
    ]
