# Generated by Django 3.2 on 2021-11-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_auto_20211117_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmap',
            name='point',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='general_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novelmap'),
        ),
    ]
