# Generated by Django 3.2 on 2021-11-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0021_auto_20211118_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='general_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_map', to='novel.novelmap'),
        ),
    ]
