# Generated by Django 4.1.7 on 2023-03-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelmodel',
            old_name='pubished',
            new_name='published',
        ),
    ]
