# Generated by Django 4.1.7 on 2023-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novelmodel_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='genre',
            field=models.ManyToManyField(to='novels.genre'),
        ),
    ]
