# Generated by Django 4.1.7 on 2023-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('novels', '0004_genre_novelmodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='authors.authormodel'),
        ),
    ]
