# Generated by Django 4.1.7 on 2023-04-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novelmodel_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='maptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='novels.maptype'),
        ),
    ]
